# Generated by Django 4.2.20 on 2025-05-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat',
            old_name='bpm',
            new_name='value',
        ),
    ]
